/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hong.recog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FriendshipRecognition service. Represents a row in the &quot;RECOG_FriendshipRecognition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hong.recog.model.impl.FriendshipRecognitionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hong.recog.model.impl.FriendshipRecognitionImpl</code>.
 * </p>
 *
 * @author hong
 * @see FriendshipRecognition
 * @generated
 */
@ProviderType
public interface FriendshipRecognitionModel
	extends BaseModel<FriendshipRecognition>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a friendship recognition model instance should use the {@link FriendshipRecognition} interface instead.
	 */

	/**
	 * Returns the primary key of this friendship recognition.
	 *
	 * @return the primary key of this friendship recognition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this friendship recognition.
	 *
	 * @param primaryKey the primary key of this friendship recognition
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this friendship recognition.
	 *
	 * @return the mvcc version of this friendship recognition
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this friendship recognition.
	 *
	 * @param mvccVersion the mvcc version of this friendship recognition
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this friendship recognition.
	 *
	 * @return the uuid of this friendship recognition
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this friendship recognition.
	 *
	 * @param uuid the uuid of this friendship recognition
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the recognition ID of this friendship recognition.
	 *
	 * @return the recognition ID of this friendship recognition
	 */
	public long getRecognitionId();

	/**
	 * Sets the recognition ID of this friendship recognition.
	 *
	 * @param recognitionId the recognition ID of this friendship recognition
	 */
	public void setRecognitionId(long recognitionId);

	/**
	 * Returns the detail a of this friendship recognition.
	 *
	 * @return the detail a of this friendship recognition
	 */
	@AutoEscape
	public String getDetailA();

	/**
	 * Sets the detail a of this friendship recognition.
	 *
	 * @param detailA the detail a of this friendship recognition
	 */
	public void setDetailA(String detailA);

	/**
	 * Returns the detail b of this friendship recognition.
	 *
	 * @return the detail b of this friendship recognition
	 */
	@AutoEscape
	public String getDetailB();

	/**
	 * Sets the detail b of this friendship recognition.
	 *
	 * @param detailB the detail b of this friendship recognition
	 */
	public void setDetailB(String detailB);

	/**
	 * Returns the detail c of this friendship recognition.
	 *
	 * @return the detail c of this friendship recognition
	 */
	@AutoEscape
	public String getDetailC();

	/**
	 * Sets the detail c of this friendship recognition.
	 *
	 * @param detailC the detail c of this friendship recognition
	 */
	public void setDetailC(String detailC);

}