/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hong.recog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Recognition service. Represents a row in the &quot;RECOG_Recognition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hong.recog.model.impl.RecognitionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hong.recog.model.impl.RecognitionImpl</code>.
 * </p>
 *
 * @author hong
 * @see Recognition
 * @generated
 */
@ProviderType
public interface RecognitionModel
	extends BaseModel<Recognition>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recognition model instance should use the {@link Recognition} interface instead.
	 */

	/**
	 * Returns the primary key of this recognition.
	 *
	 * @return the primary key of this recognition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this recognition.
	 *
	 * @param primaryKey the primary key of this recognition
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this recognition.
	 *
	 * @return the mvcc version of this recognition
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this recognition.
	 *
	 * @param mvccVersion the mvcc version of this recognition
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this recognition.
	 *
	 * @return the uuid of this recognition
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this recognition.
	 *
	 * @param uuid the uuid of this recognition
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the recognition ID of this recognition.
	 *
	 * @return the recognition ID of this recognition
	 */
	public long getRecognitionId();

	/**
	 * Sets the recognition ID of this recognition.
	 *
	 * @param recognitionId the recognition ID of this recognition
	 */
	public void setRecognitionId(long recognitionId);

	/**
	 * Returns the company ID of this recognition.
	 *
	 * @return the company ID of this recognition
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this recognition.
	 *
	 * @param companyId the company ID of this recognition
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this recognition.
	 *
	 * @return the group ID of this recognition
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this recognition.
	 *
	 * @param groupId the group ID of this recognition
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this recognition.
	 *
	 * @return the user ID of this recognition
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this recognition.
	 *
	 * @param userId the user ID of this recognition
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this recognition.
	 *
	 * @return the user uuid of this recognition
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this recognition.
	 *
	 * @param userUuid the user uuid of this recognition
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this recognition.
	 *
	 * @return the user name of this recognition
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this recognition.
	 *
	 * @param userName the user name of this recognition
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this recognition.
	 *
	 * @return the create date of this recognition
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this recognition.
	 *
	 * @param createDate the create date of this recognition
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this recognition.
	 *
	 * @return the modified date of this recognition
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this recognition.
	 *
	 * @param modifiedDate the modified date of this recognition
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the to user ID of this recognition.
	 *
	 * @return the to user ID of this recognition
	 */
	public long getToUserId();

	/**
	 * Sets the to user ID of this recognition.
	 *
	 * @param toUserId the to user ID of this recognition
	 */
	public void setToUserId(long toUserId);

	/**
	 * Returns the to user uuid of this recognition.
	 *
	 * @return the to user uuid of this recognition
	 */
	public String getToUserUuid();

	/**
	 * Sets the to user uuid of this recognition.
	 *
	 * @param toUserUuid the to user uuid of this recognition
	 */
	public void setToUserUuid(String toUserUuid);

	/**
	 * Returns the to user name of this recognition.
	 *
	 * @return the to user name of this recognition
	 */
	@AutoEscape
	public String getToUserName();

	/**
	 * Sets the to user name of this recognition.
	 *
	 * @param toUserName the to user name of this recognition
	 */
	public void setToUserName(String toUserName);

	/**
	 * Returns the value of this recognition.
	 *
	 * @return the value of this recognition
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this recognition.
	 *
	 * @param value the value of this recognition
	 */
	public void setValue(String value);

	/**
	 * Returns the subject of this recognition.
	 *
	 * @return the subject of this recognition
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this recognition.
	 *
	 * @param subject the subject of this recognition
	 */
	public void setSubject(String subject);

}