/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hong.recog.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import hong.recog.model.PerformanceRecognition;
import hong.recog.model.PerformanceRecognitionModel;
import hong.recog.model.PerformanceRecognitionSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PerformanceRecognition service. Represents a row in the &quot;RECOG_PerformanceRecognition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PerformanceRecognitionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PerformanceRecognitionImpl}.
 * </p>
 *
 * @author hong
 * @see PerformanceRecognitionImpl
 * @generated
 */
@JSON(strict = true)
public class PerformanceRecognitionModelImpl
	extends BaseModelImpl<PerformanceRecognition>
	implements PerformanceRecognitionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a performance recognition model instance should use the <code>PerformanceRecognition</code> interface instead.
	 */
	public static final String TABLE_NAME = "RECOG_PerformanceRecognition";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"recognitionId", Types.BIGINT}, {"detail1", Types.VARCHAR},
		{"detail2", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("recognitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("detail1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("detail2", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RECOG_PerformanceRecognition (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,recognitionId LONG not null primary key,detail1 VARCHAR(75) null,detail2 VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table RECOG_PerformanceRecognition";

	public static final String ORDER_BY_JPQL =
		" ORDER BY performanceRecognition.recognitionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RECOG_PerformanceRecognition.recognitionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long RECOGNITIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static PerformanceRecognition toModel(
		PerformanceRecognitionSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		PerformanceRecognition model = new PerformanceRecognitionImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setRecognitionId(soapModel.getRecognitionId());
		model.setDetail1(soapModel.getDetail1());
		model.setDetail2(soapModel.getDetail2());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<PerformanceRecognition> toModels(
		PerformanceRecognitionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<PerformanceRecognition> models =
			new ArrayList<PerformanceRecognition>(soapModels.length);

		for (PerformanceRecognitionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PerformanceRecognitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _recognitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRecognitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _recognitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PerformanceRecognition.class;
	}

	@Override
	public String getModelClassName() {
		return PerformanceRecognition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PerformanceRecognition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PerformanceRecognition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PerformanceRecognition, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PerformanceRecognition)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PerformanceRecognition, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PerformanceRecognition, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PerformanceRecognition)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PerformanceRecognition, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PerformanceRecognition, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PerformanceRecognition>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PerformanceRecognition.class.getClassLoader(),
			PerformanceRecognition.class, ModelWrapper.class);

		try {
			Constructor<PerformanceRecognition> constructor =
				(Constructor<PerformanceRecognition>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PerformanceRecognition, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PerformanceRecognition, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PerformanceRecognition, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PerformanceRecognition, Object>>();
		Map<String, BiConsumer<PerformanceRecognition, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<PerformanceRecognition, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", PerformanceRecognition::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<PerformanceRecognition, Long>)
				PerformanceRecognition::setMvccVersion);
		attributeGetterFunctions.put("uuid", PerformanceRecognition::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PerformanceRecognition, String>)
				PerformanceRecognition::setUuid);
		attributeGetterFunctions.put(
			"recognitionId", PerformanceRecognition::getRecognitionId);
		attributeSetterBiConsumers.put(
			"recognitionId",
			(BiConsumer<PerformanceRecognition, Long>)
				PerformanceRecognition::setRecognitionId);
		attributeGetterFunctions.put(
			"detail1", PerformanceRecognition::getDetail1);
		attributeSetterBiConsumers.put(
			"detail1",
			(BiConsumer<PerformanceRecognition, String>)
				PerformanceRecognition::setDetail1);
		attributeGetterFunctions.put(
			"detail2", PerformanceRecognition::getDetail2);
		attributeSetterBiConsumers.put(
			"detail2",
			(BiConsumer<PerformanceRecognition, String>)
				PerformanceRecognition::setDetail2);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getRecognitionId() {
		return _recognitionId;
	}

	@Override
	public void setRecognitionId(long recognitionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recognitionId = recognitionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRecognitionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("recognitionId"));
	}

	@JSON
	@Override
	public String getDetail1() {
		if (_detail1 == null) {
			return "";
		}
		else {
			return _detail1;
		}
	}

	@Override
	public void setDetail1(String detail1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detail1 = detail1;
	}

	@JSON
	@Override
	public String getDetail2() {
		if (_detail2 == null) {
			return "";
		}
		else {
			return _detail2;
		}
	}

	@Override
	public void setDetail2(String detail2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detail2 = detail2;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PerformanceRecognition.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PerformanceRecognition toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PerformanceRecognition>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PerformanceRecognitionImpl performanceRecognitionImpl =
			new PerformanceRecognitionImpl();

		performanceRecognitionImpl.setMvccVersion(getMvccVersion());
		performanceRecognitionImpl.setUuid(getUuid());
		performanceRecognitionImpl.setRecognitionId(getRecognitionId());
		performanceRecognitionImpl.setDetail1(getDetail1());
		performanceRecognitionImpl.setDetail2(getDetail2());

		performanceRecognitionImpl.resetOriginalValues();

		return performanceRecognitionImpl;
	}

	@Override
	public int compareTo(PerformanceRecognition performanceRecognition) {
		long primaryKey = performanceRecognition.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PerformanceRecognition)) {
			return false;
		}

		PerformanceRecognition performanceRecognition =
			(PerformanceRecognition)object;

		long primaryKey = performanceRecognition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PerformanceRecognition> toCacheModel() {
		PerformanceRecognitionCacheModel performanceRecognitionCacheModel =
			new PerformanceRecognitionCacheModel();

		performanceRecognitionCacheModel.mvccVersion = getMvccVersion();

		performanceRecognitionCacheModel.uuid = getUuid();

		String uuid = performanceRecognitionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			performanceRecognitionCacheModel.uuid = null;
		}

		performanceRecognitionCacheModel.recognitionId = getRecognitionId();

		performanceRecognitionCacheModel.detail1 = getDetail1();

		String detail1 = performanceRecognitionCacheModel.detail1;

		if ((detail1 != null) && (detail1.length() == 0)) {
			performanceRecognitionCacheModel.detail1 = null;
		}

		performanceRecognitionCacheModel.detail2 = getDetail2();

		String detail2 = performanceRecognitionCacheModel.detail2;

		if ((detail2 != null) && (detail2.length() == 0)) {
			performanceRecognitionCacheModel.detail2 = null;
		}

		return performanceRecognitionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PerformanceRecognition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PerformanceRecognition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PerformanceRecognition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((PerformanceRecognition)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PerformanceRecognition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PerformanceRecognition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PerformanceRecognition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((PerformanceRecognition)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PerformanceRecognition>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private String _uuid;
	private long _recognitionId;
	private String _detail1;
	private String _detail2;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PerformanceRecognition, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PerformanceRecognition)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("recognitionId", _recognitionId);
		_columnOriginalValues.put("detail1", _detail1);
		_columnOriginalValues.put("detail2", _detail2);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("recognitionId", 4L);

		columnBitmasks.put("detail1", 8L);

		columnBitmasks.put("detail2", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PerformanceRecognition _escapedModel;

}